version: "3"

services:
  registry:
    build:
      context: ./  #Parto dalla root del progetto
      dockerfile: ./DockerFiles/registry/Dockerfile  #path del docker file associato al registry
    ports:
      - "1234:1234"  # Mappa la porta 1234 del server del container all'host
    networks:
      - my_network

  node1:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8005:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node2:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8006:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node3:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8007:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node4:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8008:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node5:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8009:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node6:
    build:
      context: ./ 
      dockerfile: ./DockerFiles/node/Dockerfile  
    ports:
      - "8010:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

networks:
  my_network:
    driver: bridge
