version: '3'
services:
  registry:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/registry/Dockerfile  # Percorso corretto per il Dockerfile del server
    ports:
      - "1234:1234"  # Mappa la porta 1234 del server del container all'host
    # Altri comandi o opzioni del server, se necessario


  node:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorso corretto per il Dockerfile del server
    # Altri comandi o opzioni del nodo, se necessario

