version: "3"

services:
  registry:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/registry/Dockerfile  # Percorso corretto per il Dockerfile del server
    ports:
      - "1234:1234"  # Mappa la porta 1234 del server del container all'host
    networks:
      - my_network

  node1:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorto corretto per il Dockerfile del server
    ports:
      - "8005:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node2:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorto corretto per il Dockerfile del server
    ports:
      - "8006:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node3:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorto corretto per il Dockerfile del server
    ports:
      - "8007:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node4:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorto corretto per il Dockerfile del server
    ports:
      - "8008:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

  node5:
    build:
      context: ./  # Percorso corretto per il contesto del Dockerfile del server
      dockerfile: ./DockerFiles/node/Dockerfile  # Percorto corretto per il Dockerfile del server
    ports:
      - "8009:8005"  # Mappa la porta 8005 del server del container all'host
    networks:
      - my_network
    depends_on:
      - registry

networks:
  my_network:
    driver: bridge
